# Generated by Django 3.0.2 on 2020-02-02 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('name', models.CharField(default=None, max_length=15)),
                ('center_id', models.CharField(default='f9aec', editable=False, max_length=5, primary_key=True, serialize=False)),
                ('voiceit_id', models.CharField(default=None, max_length=40)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/None/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_office_admin', models.NullBooleanField(default=None)),
                ('voiceit_id', models.CharField(default=None, max_length=40)),
                ('contact_number', models.CharField(default=None, max_length=11)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Centers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('location_verified', models.NullBooleanField(default=None)),
                ('voice_face_verified', models.NullBooleanField(default=None)),
                ('present', models.NullBooleanField(default=None)),
                ('status', models.CharField(blank=True, default='Not Present', max_length=30)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Centers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
