# Generated by Django 3.0.2 on 2020-02-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancetable',
            old_name='face_verified',
            new_name='present',
        ),
        migrations.RenameField(
            model_name='attendancetable',
            old_name='voice_verified',
            new_name='voice_face_verified',
        ),
        migrations.AddField(
            model_name='centers',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='centers',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancetable',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='centers',
            name='center_id',
            field=models.CharField(default='b0dd6', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
