# Generated by Django 3.0.2 on 2020-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Center',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_Admin',
            new_name='is_office_admin',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='voiceit_id',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
