# Generated by Django 3.0.2 on 2020-02-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20200202_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='center_id',
            field=models.CharField(default='f356f', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
