# Generated by Django 3.0.2 on 2020-02-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_auto_20200202_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='center_id',
            field=models.CharField(default='46543', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
