# Generated by Django 3.0.2 on 2020-02-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_auto_20200202_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancetable',
            name='status',
            field=models.CharField(blank=True, default='Not Present', max_length=30),
        ),
        migrations.AlterField(
            model_name='centers',
            name='center_id',
            field=models.CharField(default='89127', editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
